# Generated by Django 6.0.1 on 2026-01-25 22:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Fecha de la Jornada')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('Lb', 'Libra'), ('Und', 'Unidad')], default='Und', max_length=5)),
                ('formato_visual', models.CharField(choices=[('moneda', 'Pesos Colombianos ($)'), ('unidades', 'Unidades (Puntos de mil)')], default='unidades', max_length=10, verbose_name='Formato de ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ControlZonaJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cerrada', models.BooleanField(default=False, verbose_name='¿Cerró Jornada?')),
                ('nombre_vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('dinero_entregado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.jornada')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.zona')),
            ],
            options={
                'verbose_name': 'Control de Zona',
                'verbose_name_plural': 'Controles de Zonas',
                'unique_together': {('jornada', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='InventarioControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_salida', models.IntegerField(default=0)),
                ('cantidad_llegada', models.IntegerField(default=0)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_ventas.controlzonajornada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad_salida', models.IntegerField(verbose_name='Carga Inicial')),
                ('cantidad_llegada', models.IntegerField(default=0, verbose_name='Regresó a Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.producto')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.zona')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioInterzona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('aceptado', models.BooleanField(default=False)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='gestion_ventas.jornada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_ventas.producto')),
                ('zona_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_entrantes', to='gestion_ventas.zona')),
                ('zona_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_salientes', to='gestion_ventas.zona')),
            ],
        ),
    ]
