# Generated by Django 6.0.1 on 2026-04-03 20:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='controlzonajornada',
            options={'ordering': ['-jornada__fecha', 'zona__nombre'], 'verbose_name': 'Control de Zona', 'verbose_name_plural': 'Controles de Zonas'},
        ),
        migrations.AlterModelOptions(
            name='enviointerzona',
            options={'ordering': ['-fecha'], 'verbose_name': 'Envío Interzona', 'verbose_name_plural': 'Envíos Interzona'},
        ),
        migrations.AlterModelOptions(
            name='inventariocontrol',
            options={'verbose_name': 'Inventario de Jornada', 'verbose_name_plural': 'Inventarios de Jornada'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='registroventa',
            options={'ordering': ['-fecha', 'zona__nombre'], 'verbose_name': 'Registro de Venta', 'verbose_name_plural': 'Registros de Venta'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['nombre'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.AddField(
            model_name='jornada',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='jornada',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registroventa',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_venta', to='gestion_ventas.jornada'),
        ),
        migrations.AddField(
            model_name='zona',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la Jornada'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='jornada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='gestion_ventas.cliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='gestion_ventas.cliente'),
        ),
        migrations.AddField(
            model_name='zona',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='gestion_ventas.cliente'),
        ),
        migrations.AddConstraint(
            model_name='jornada',
            constraint=models.UniqueConstraint(fields=('cliente', 'fecha'), name='unique_jornada_por_cliente_y_fecha'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='gestion_ventas.cliente'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='zona_preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_preferidos', to='gestion_ventas.zona'),
        ),
        migrations.AddField(
            model_name='controlzonajornada',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='gestion_ventas.vendedor'),
        ),
    ]
