# Generated by Django 6.0.1 on 2026-04-03 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0002_vendedor_alter_controlzonajornada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='gestion_ventas.controlzonajornada')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='gestion_ventas.vendedor')),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
