# Generated by Django 6.0.1 on 2026-04-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0003_producto_precio_venta_adelanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaProductoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_zona', to='gestion_ventas.producto')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_producto', to='gestion_ventas.zona')),
            ],
            options={
                'verbose_name': 'Comision por producto en zona',
                'verbose_name_plural': 'Comisiones por producto en zona',
                'ordering': ['producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('zona', 'producto'), name='unique_comision_producto_por_zona')],
            },
        ),
    ]
