# Generated by Django 6.0.1 on 2026-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ventas', '0004_zonaproductocomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariocontrol',
            name='evidencia_salida',
            field=models.FileField(blank=True, null=True, upload_to='inventario_evidencias/'),
        ),
    ]
